#!/usr/bin/env python3
"""Prove the desert-reskin winner map is honest: for every asset in
art_candidates/desert_reskin/manifest.json, hash the recorded "winner"
variant and the live assets/art/ sprite it claims to have shipped, and
fail if they ever diverge (hand-edited sprite, bumped winner without
re-running tools/apply_desert_winner.py, etc).

Usage:
    python3 tools/verify_desert_winners.py
    python3 tools/verify_desert_winners.py --markdown       # print the
        audit table only
    python3 tools/verify_desert_winners.py --write-winners  # regenerate
        AND splice the table directly into winners.md between the
        AUDIT_TABLE markers -- no manual copy-paste, so the table in
        winners.md can never drift from what this script just measured.

PROJECT_ROOT and MANIFEST are module attributes (not baked into main())
so tests can monkeypatch them onto a scratch tree.
"""
import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = PROJECT_ROOT / "art_candidates" / "desert_reskin" / "manifest.json"
WINNERS_MD = PROJECT_ROOT / "art_reviews" / "desert_reskin" / "winners.md"
AUDIT_START = "<!-- AUDIT_TABLE_START (generated by tools/verify_desert_winners.py --write-winners) -->"
AUDIT_END = "<!-- AUDIT_TABLE_END -->"


def md5(path: Path) -> str:
    return hashlib.md5(path.read_bytes()).hexdigest()


def check_winners(manifest_path: Path, project_root: Path):
    """Returns (rows, mismatches). Each row is
    (name, winner, src_md5, dest_md5, match: bool)."""
    manifest = json.loads(manifest_path.read_text())
    cand_root = manifest_path.parent

    rows = []
    mismatches = []
    for name, entry in manifest.items():
        if name == "backend_legend":
            continue
        winner = entry.get("winner")
        if winner is None:
            continue
        variants = entry["variants"]
        if not (1 <= winner <= len(variants)):
            mismatches.append(f"{name}: winner={winner!r} out of range for {len(variants)} variant(s)")
            continue
        src = cand_root / variants[winner - 1]["path"]
        dest = project_root / entry["replaces"]
        if not src.exists():
            mismatches.append(f"{name}: recorded winner variant {src} does not exist")
            continue
        if not dest.exists():
            mismatches.append(f"{name}: {dest} does not exist")
            continue
        src_md5, dest_md5 = md5(src), md5(dest)
        rows.append((name, winner, src_md5, dest_md5, src_md5 == dest_md5))
        if src_md5 != dest_md5:
            mismatches.append(f"{name}: recorded winner {src} does not match shipped {dest}")

    return rows, mismatches


def render_markdown_table(rows) -> str:
    lines = ["| asset | winner | variant md5 | live sprite md5 | match |",
             "|---|---|---|---|---|"]
    for name, winner, src_md5, dest_md5, ok in rows:
        lines.append(f"| {name} | {winner} | `{src_md5[:8]}...` | `{dest_md5[:8]}...` | {'yes' if ok else 'NO'} |")
    return "\n".join(lines)


def write_into_winners_md(table: str, winners_md: Path = None) -> None:
    # winners_md defaults to None (not `= WINNERS_MD`) deliberately: a
    # default bound at def-time would freeze in the module-load-time path
    # and ignore a later `verify_desert_winners.WINNERS_MD = ...`
    # monkeypatch (exactly the kind tests use to target a scratch file).
    if winners_md is None:
        winners_md = WINNERS_MD
    text = winners_md.read_text()
    pattern = re.compile(re.escape(AUDIT_START) + r".*?" + re.escape(AUDIT_END), re.DOTALL)
    replacement = f"{AUDIT_START}\n{table}\n{AUDIT_END}"
    new_text, count = pattern.subn(replacement, text)
    if count != 1:
        raise ValueError(f"expected exactly one {AUDIT_START}...{AUDIT_END} block in {winners_md}, found {count}")
    winners_md.write_text(new_text)


def main(argv=None) -> int:
    # argv is threaded through explicitly (rather than tests monkeypatching
    # sys.argv) so main() is directly callable from a test with a plain
    # list of args, no ambient global to save/restore.
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", default=str(MANIFEST))
    ap.add_argument("--project-root", default=str(PROJECT_ROOT),
                    help="root that --manifest's \"replaces\" paths are relative to "
                         "(defaults to this repo; override together with --manifest "
                         "when pointing at a scratch tree)")
    ap.add_argument("--markdown", action="store_true",
                    help="print the winners.md audit table instead of the plain log")
    ap.add_argument("--write-winners", action="store_true",
                    help="splice the freshly-measured audit table into winners.md in place")
    args = ap.parse_args(argv)
    project_root = Path(args.project_root)

    rows, mismatches = check_winners(Path(args.manifest), project_root)

    if args.write_winners:
        # Always derived the same way from project_root (which defaults to
        # PROJECT_ROOT) -- no special-casing needed between "real repo" and
        # "scratch tree pointed at via --project-root" runs.
        winners_md = project_root / "art_reviews" / "desert_reskin" / "winners.md"
        write_into_winners_md(render_markdown_table(rows), winners_md)
        print(f"wrote {len(rows)}-row audit table into {winners_md}")
    elif args.markdown:
        print(render_markdown_table(rows))
    else:
        for name, winner, src_md5, dest_md5, ok in rows:
            print(f"{name}: winner={winner} variant_md5={src_md5[:8]} live_md5={dest_md5[:8]} "
                  f"match={'yes' if ok else 'NO'}")

    if mismatches:
        print(f"\n{len(mismatches)} mismatch(es):", file=sys.stderr)
        for m in mismatches:
            print(f"  {m}", file=sys.stderr)
        return 1

    print(f"\n{len(rows)} asset(s) verified -- manifest winners match what's shipped.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
